Use main coverallsapp gh

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,26 +34,32 @@ jobs:
               uses: actions/checkout@v3
 
             - name: Test
+              env:
+                  COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               run: |
                   go test -race -covermode atomic -coverprofile coverage.out ./...
                   go tool cover -func coverage.out
 
-            # - name: Quality Gate - Test coverage shall be above threshold
-            #   run: |
-            #       echo "Quality Gate: checking test coverage is above threshold ..."
-            #       echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
-            #       totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
-            #       echo "Current test coverage : $totalCoverage %"
-            #       if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
-            #           echo "OK"
-            #       else
-            #           echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
-            #           echo "Failed"
-            #           exit 1
-            #       fi
+            - name: Quality Gate - Test coverage shall be above threshold
+              run: |
+                  echo "Quality Gate: checking test coverage is above threshold ..."
+                  echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+                  totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+                  echo "Current test coverage : $totalCoverage %"
+                  if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+                      echo "OK"
+                  else
+                      echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+                      echo "Failed"
+                      exit 1
+                  fi
 
-            - name: Upload coverage to Codecov
-              uses: codecov/codecov-action@v3
+            - name: Coveralls
+              uses: coverallsapp/github-action@master
+              with:
+                  github-token: ${{ secrets.GITHUB_TOKEN }}
+                  path-to-lcov: ./coverage.out
+                  flag-name: run-${{ matrix.test_number }}
 
     lint:
         name: Lint
