Update Codecov

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,19 +38,22 @@ jobs:
                   go test -race -covermode atomic -coverprofile coverage.out ./...
                   go tool cover -func coverage.out
 
-            - name: Quality Gate - Test coverage shall be above threshold
-              run: |
-                  echo "Quality Gate: checking test coverage is above threshold ..."
-                  echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
-                  totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
-                  echo "Current test coverage : $totalCoverage %"
-                  if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
-                      echo "OK"
-                  else
-                      echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
-                      echo "Failed"
-                      exit 1
-                  fi
+            # - name: Quality Gate - Test coverage shall be above threshold
+            #   run: |
+            #       echo "Quality Gate: checking test coverage is above threshold ..."
+            #       echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+            #       totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            #       echo "Current test coverage : $totalCoverage %"
+            #       if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+            #           echo "OK"
+            #       else
+            #           echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+            #           echo "Failed"
+            #           exit 1
+            #       fi
+
+            - name: Upload coverage to Codecov
+              uses: codecov/codecov-action@v3
 
     lint:
         name: Lint
